In [6]:
from pathlib import Path
import pandas as pd

DATA_DIR = Path().resolve().parent / "Data"
data_file = "train_test_network.csv"
data_path = DATA_DIR / data_file

df = pd.read_csv(data_path, na_values=[' '])
df.head()

,src_ip,src_port,dst_ip,dst_port,proto,service,duration,src_bytes,dst_bytes,conn_state,...,http_response_body_len,http_status_code,http_user_agent,http_orig_mime_types,http_resp_mime_types,weird_name,weird_addl,weird_notice,label,type
0,192.168.1.37,4444,192.168.1.193,49178,tcp,-,290.371539,101568,2592,OTH,...,0,0,-,-,-,-,-,-,1,backdoor
1,192.168.1.193,49180,192.168.1.37,8080,tcp,-,0.000102,0,0,REJ,...,0,0,-,-,-,-,-,-,1,backdoor
2,192.168.1.193,49180,192.168.1.37,8080,tcp,-,0.000148,0,0,REJ,...,0,0,-,-,-,-,-,-,1,backdoor
3,192.168.1.193,49180,192.168.1.37,8080,tcp,-,0.000113,0,0,REJ,...,0,0,-,-,-,-,-,-,1,backdoor
4,192.168.1.193,49180,192.168.1.37,8080,tcp,-,0.000130,0,0,REJ,...,0,0,-,-,-,-,-,-,1,backdoor

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 211043 entries, 0 to 211042
Data columns (total 44 columns):
 #   Column                  Non-Null Count   Dtype
---  ------                  --------------   -----
 0   src_ip                  211043 non-null  object
 1   src_port                211043 non-null  int64
 2   dst_ip                  211043 non-null  object
 3   dst_port                211043 non-null  int64
 4   proto                   211043 non-null  object
 5   service                 211043 non-null  object
 6   duration                211043 non-null  float64
 7   src_bytes               211043 non-null  int64
 8   dst_bytes               211043 non-null  int64
 9   conn_state              211043 non-null  object
 10  missed_bytes            211043 non-null  int64
 11  src_pkts                211043 non-null  int64
 12  src_ip_bytes            211043 non-null  int64
 13  dst_pkts                211043 non-null  int64
 14  dst_ip_bytes            211043 non-null  int64
 15  dns_query               211043 non-null  object
 16  dns_qclass              211043 non-null  int64
 17  dns_qtype               211043 non-null  int64
 18  dns_rcode               211043 non-null  int64
 19  dns_AA                  211043 non-null  object
 20  dns_RD                  211043 non-null  object
 21  dns_RA                  211043 non-null  object
 22  dns_rejected            211043 non-null  object
 23  ssl_version             211043 non-null  object
 24  ssl_cipher              211043 non-null  object
 25  ssl_resumed             211043 non-null  object
 26  ssl_established         211043 non-null  object
 27  ssl_subject             211043 non-null  object
 28  ssl_issuer              211043 non-null  object
 29  http_trans_depth        211043 non-null  object
 30  http_method             211043 non-null  object
 31  http_uri                211043 non-null  object
 32  http_version            211043 non-null  object
 33  http_request_body_len   211043 non-null  int64
 34  http_response_body_len  211043 non-null  int64
 35  http_status_code        211043 non-null  int64
 36  http_user_agent         211043 non-null  object
 37  http_orig_mime_types    211043 non-null  object
 38  http_resp_mime_types    211043 non-null  object
 39  weird_name              211043 non-null  object
 40  weird_addl              211043 non-null  object
 41  weird_notice            211043 non-null  object
 42  label                   211043 non-null  int64
 43  type                    211043 non-null  object
dtypes: float64(1), int64(16), object(27)
memory usage: 70.8+ MB

In [9]:
df.describe().T

,count,mean,std,min,25%,50%,75%,max
src_port,211043.0,38646.519543,1.930727e+04,1.0,34608.0,44754.00000,51133.000000,6.552800e+04
dst_port,211043.0,3495.153770,1.019162e+04,0.0,65.0,80.00000,1253.000000,6.546700e+04
duration,211043.0,7.700887,5.641419e+02,0.0,0.0,0.00017,0.054196,9.351693e+04
src_bytes,211043.0,258113.564274,1.709490e+07,0.0,0.0,0.00000,130.000000,3.890855e+09
dst_bytes,211043.0,258804.571575,1.802563e+07,0.0,0.0,0.00000,89.000000,3.913853e+09
missed_bytes,211043.0,34432.344295,5.261621e+06,0.0,0.0,0.00000,0.000000,1.854527e+09
src_pkts,211043.0,9.595220,9.177882e+01,0.0,1.0,1.00000,4.000000,2.462300e+04
src_ip_bytes,211043.0,776.082206,2.229703e+04,0.0,48.0,82.00000,415.000000,6.522626e+06
dst_pkts,211043.0,3.846861,3.307058e+02,0.0,0.0,1.00000,2.000000,1.219420e+05
dst_ip_bytes,211043.0,1584.686628,1.901795e+05,0.0,0.0,40.00000,134.000000,8.639552e+07
dns_qclass,211043.0,227.630805,2.720714e+03,0.0,0.0,0.00000,0.000000,3.276900e+04
dns_qtype,211043.0,3.610909,2.379775e+01,0.0,0.0,0.00000,0.000000,2.550000e+02
dns_rcode,211043.0,0.123989,5.988042e-01,0.0,0.0,0.00000,0.000000,5.000000e+00
http_request_body_len,211043.0,0.065418,9.243405e+00,0.0,0.0,0.00000,0.000000,2.338000e+03
http_response_body_len,211043.0,144.929531,3.047244e+04,0.0,0.0,0.00000,0.000000,1.342438e+07
http_status_code,211043.0,0.303905,8.270377e+00,0.0,0.0,0.00000,0.000000,4.040000e+02
label,211043.0,0.763081,4.251929e-01,0.0,1.0,1.00000,1.000000,1.000000e+00

In [10]:
df.describe(include='object').T

                       count unique            top    freq
src_ip                211043     51   192.168.1.30   61633
dst_ip                211043    753  192.168.1.190   47795
proto                 211043      3            tcp  168747
service               211043      9              -  132032
conn_state            211043     13             S0   51937
dns_query             211043    726              -  176198
dns_AA                211043      3              -  176030
dns_RD                211043      3              -  176030
dns_RA                211043      3              -  176030
dns_rejected          211043      3              -  176030
ssl_version           211043      4              -  210642
ssl_cipher            211043      6              -  210642
ssl_resumed           211043      3              -  210642
ssl_established       211043      3              -  210642
ssl_subject           211043      6              -  211032
ssl_issuer            211043      5              -  211032
http_trans_depth      211043     11              -  210740
http_method           211043      4              -  210756
http_uri              211043     86              -  210756
http_version          211043      2              -  210745
http_user_agent       211043     35              -  210756
http_orig_mime_types  211043      3              -  211027
http_resp_mime_types  211043     10              -  210839
weird_name            211043     11              -  210687
weird_addl            211043      3              -  210886
weird_notice          211043      2              -  210687
type                  211043     10         normal   50000